AllCops:
  TargetRubyVersion: 2.2
Documentation:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'configure']
Metrics/MethodLength:
  Max: 15
Style/CommentedKeyword:
  Enabled: false
